# Generated by Django 2.1.3 on 2018-11-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='course_id',
            new_name='course',
        ),
    ]
