# Generated by Django 2.1.3 on 2018-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20181125_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isNotes',
            field=models.BooleanField(default=True),
        ),
    ]
