# Generated by Django 2.1.3 on 2019-03-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Branch', '0002_auto_20190114_2002'),
    ]

    operations = [
    ]
