# Generated by Django 2.1.3 on 2018-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POINTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_upvote', models.IntegerField(default=5)),
                ('notes_dowvote', models.IntegerField(default=-2)),
                ('assignments_upvote', models.IntegerField(default=10)),
                ('assignments_downvote', models.IntegerField(default=-3)),
            ],
        ),
    ]
