# Generated by Django 2.1.3 on 2018-11-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='notes_dowvote',
            new_name='notes_downvote',
        ),
    ]
